title: Song Ziqi
description: PhD Student at Nankai University, working on micro/nano devices and device physics.
url: "https://ziqi-ee.github.io"
baseurl: ""
lang: en
timezone: Asia/Shanghai

markdown: kramdown
permalink: pretty

exclude:
  - README.md
